# Generated by Django 3.1.4 on 2020-12-30 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
